version: '3'
services:
  db-product:
    container_name: db-product
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: nico
      POSTGRES_PASSWORD: nico
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431